heat_template_version: 2013-05-23

description: >

  Version: 2014.1.2
  This is a template to test the Orchestration service

resources:

  heat_vm:
    type: OS::Nova::Server
    properties:
      name : heat-vm
      image: cirros-0.3.4
      flavor: m1.tiny
      networks:
        - network: net1

  heat_volume:
    type: OS::Cinder::Volume
    properties:
      name: heat-vol
      size: 1

  heat_volume_attached:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: {get_resource: heat_vm}
      volume_id: {get_resource: heat_volume}
      mountpoint: /dev/xvda3

  heat_float_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  heat_float_assoc:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: heat_float_ip}
      server_id: {get_resource: heat_vm}

outputs:
  floating_ip:
    description: Allocated Floating IP
    value: {get_attr : [heat_float_ip, ip]}